name: Libtorrent Build Matrix

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build - ${{ matrix.config }}
        runs-on: ubuntu-22.04
        continue-on-error: true
        strategy:
            matrix:
                config:
                    - 'asio-debugging=on picker-debugging=on'
                    - 'extensions=off logging=off streaming=off super-seeding=off share-mode=off predictive-pieces=off dht=off alert-msg=off encryption=off mutable-torrents=off deprecated-functions=off'
                    - 'crypto=gcrypt'
                    - 'mmap-disk-io=off'
            fail-fast: false

        steps:
            - name: Checkout repository
              run: git clone https://github.com/arvidn/libtorrent.git --depth 1 --branch RC_2_0

            - name: Update package lists
              run: sudo apt update
              continue-on-error: true

            - name: Setup ccache
              uses: Chocobo1/setup-ccache-action@v1
              with:
                  update_packager_index: false
                  override_cache_key: ccache-linux-build-${{ github.base_ref }}-${{ matrix.config }}
                  ccache_options: |
                      max_size=5G

            - name: Install dependencies
              run: |
                  sudo apt install -y \
                    libboost-python-dev \
                    libboost-tools-dev \
                    libboost-dev \
                    libboost-system-dev \
                    python3
                  echo "using gcc ;" >> ~/user-config.jam

            - name: Install gcrypt (if needed)
              if: contains(matrix.config, 'crypto=gcrypt')
              run: sudo apt install -y libgcrypt20-dev

            - name: Build library
              run: b2 ${{ matrix.config }} cxxstd=14,17,20 warnings-as-errors=on

            - name: Build examples
              run: |
                  cd examples
                  b2 ${{ matrix.config }} cxxstd=14,17,20 warnings-as-errors=on

            - name: Build tools
              run: |
                  cd tools
                  b2 ${{ matrix.config }} cxxstd=14,17,20 warnings-as-errors=on

            - name: Build Python bindings
              run: |
                  cd bindings/python
                  echo "using python ;" >> ~/user-config.jam
                  BOOST_ROOT="" b2 ${{ matrix.config }} cxxstd=14,17,20 warnings-as-errors=on
