name: Build Python Bindings


on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-python-bindings:
    runs-on: windows-latest
    env:
      BOOST_ROOT: C:\\Libraries\\boost_1_83_0
      BOOST_BUILD_PATH: ${{ env.BOOST_ROOT }}\\tools\\build
      SSL_LIB: C:\\OpenSSL-v111-Win64\\lib
      SSL_INCLUDE: C:\\OpenSSL-v111-Win64\\include
      ROOT_DIRECTORY: ${{ github.workspace }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
        architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install websockets

    - name: Install OpenSSL
      run: |
        $url = "https://slproweb.com/download/Win64OpenSSL-1_1_1w.exe"
        $output = "$env:RUNNER_TEMP\Win64OpenSSL.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process $output -ArgumentList '/silent', '/verysilent', '/sp-', '/suppressmsgboxes', '/DIR=C:\OpenSSL-v111-Win64' -Wait

    - name: Download and extract Boost
      run: |
        $url = "https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.zip"
        $output = "$env:RUNNER_TEMP\boost.zip"
        New-Item -ItemType Directory -Path C:\Libraries -Force
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath C:\Libraries

    - name: Configure Boost.Build
      run: |
        $pythonDir = "$(python -c 'import sys; print(sys.prefix)')"
        $pythonVersion = "$(python -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"
        $configContent = "using msvc ;`nusing python : $pythonVersion : `"$pythonDir`" : `"$pythonDir\\include`" : `"$pythonDir\\libs`" ;"
        $configContent | Out-File -FilePath "$env:HOMEDRIVE$env:HOMEPATH\user-config.jam" -Encoding ascii
        type "$env:HOMEDRIVE$env:HOMEPATH\user-config.jam"

    - name: Build Boost.Python
      run: |
        cd $env:BOOST_BUILD_PATH
        .\bootstrap.bat
        cd $env:BOOST_ROOT
        .\b2.exe --with-python cxxstd=17 address-model=64 link=shared stage

    - name: Build libtorrent
      run: |
        cd $env:ROOT_DIRECTORY
        $env:PATH += ";$env:BOOST_BUILD_PATH"
        b2.exe openssl-lib=$env:SSL_LIB openssl-include=$env:SSL_INCLUDE variant=release compiler=msvc address-model=64 link=shared crypto=openssl webtorrent=on cxxstd=17

    - name: Build Python bindings
      run: |
        cd $env:ROOT_DIRECTORY\bindings\python
        b2.exe openssl-lib=$env:SSL_LIB openssl-include=$env:SSL_INCLUDE variant=release compiler=msvc address-model=64 link=shared crypto=openssl webtorrent=on libtorrent-link=shared stage_module

    - name: Package Python bindings
      run: |
        cd $env:ROOT_DIRECTORY\bindings\python
        python setup.py bdist --format=msi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: python-module
        path: bindings/python/dist/*.msi
