name: Python bindings

on:
    push:
    pull_request:

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
    cancel-in-progress: true

env:
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
    test:
        name: build
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-24.04, macos-latest, windows-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 1
                  filter: tree:0

            - name: dependencies (MacOS)
              if: runner.os == 'macOS'
              run: |
                  brew install boost-build boost boost-python3 python@3.13 openssl@3 python-setuptools
                  export PATH=$(brew --prefix)/opt/python@3.13/bin:$PATH

            - name: update package lists (linux)
              if: runner.os == 'Linux'
              continue-on-error: true
              run: sudo apt update

            - name: Setup ccache
              if: runner.os != 'Windows'
              uses: Chocobo1/setup-ccache-action@v1
              with:
                  update_packager_index: false
                  override_cache_key: ccache-python-${{ matrix.os }}-${{ github.base_ref }}
                  ccache_options: |
                      max_size=500M

            - name: dependencies (linux)
              if: runner.os == 'Linux'
              run: |
                  sudo apt install libboost-tools-dev libboost-python-dev libboost-dev libboost-system-dev python3 python3-setuptools libssl-dev

            - name: install boost (windows)
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                  git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
                  cd boost
                  bootstrap.bat

            - name: boost headers (windows)
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                  cd boost
                  .\b2 headers

            # New step to build libdatachannel
            - name: Build libdatachannel (Windows)
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                  cd deps\libdatachannel
                  cmake -B build -G "Visual Studio 17 2022" -A x64 -DNO_TESTS=ON -DNO_EXAMPLES=ON -DUSE_STATIC_LIB=ON
                  cmake --build build --config Release --target install

            - name: build/install (windows)
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                  set BOOST_ROOT=%CD%\boost
                  set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
                  set PATH=%BOOST_ROOT%;%PATH%
                  cd bindings/python
                  python setup.py build_ext --b2-args "msvc-version-macro=on address-model=64 asserts=on invariant-checks=full webtorrent=on crypto=openssl" install --user --prefix=

            - name: build no-deprecated (Linux)
              if: runner.os == 'Linux'
              run: |
                  cd bindings/python
                  python3 setup.py build_ext --b2-args "deprecated-functions=off webtorrent=on"

            - name: build/install (Linux)
              if: runner.os == 'Linux'
              run: |
                  cd bindings/python
                  python3 setup.py build_ext install --user --prefix=

            - name: build/install (MacOS)
              if: runner.os == 'macOS'
              run: |
                  cd bindings/python
                  export PATH=$(brew --prefix)/opt/python@3.13/bin:$PATH
                  python3.13 setup.py build_ext --b2-args "webtorrent=on" install --install-lib $(brew --prefix)/lib/python3.13/site-packages