name: Python bindings

on:
  push:
  pull_request:

env:
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]

    steps:
      - name: Download source
        run: |
          git clone https://github.com/arvidn/libtorrent.git --depth=1 --recurse-submodules --branch RC_2_0

      # === OS-specific dependencies ===
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            libboost-tools-dev libboost-python-dev libboost-dev \
            libboost-system-dev python3 python3-setuptools libssl-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install boost boost-python3 python@3.13 openssl@3 python-setuptools
          echo "$(brew --prefix)/opt/python@3.13/bin" >> $GITHUB_PATH

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
          cd boost
          ./bootstrap.bat
          ./b2 headers

      # === Build libdatachannel ===
      - name: Build libdatachannel (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd libtorrent/deps/libdatachannel
          cmake -B build -G "Visual Studio 17 2022" -A x64 `
            -DNO_TESTS=ON -DNO_EXAMPLES=ON -DUSE_STATIC_LIB=ON `
            -DCMAKE_INSTALL_PREFIX=install
          cmake --build build --config Release --target INSTALL

      # === Build Python Bindings ===

      - name: Build Python bindings (Linux)
        if: runner.os == 'Linux'
        run: |
          cd libtorrent/bindings/python
          python3 setup.py build_ext --b2-args "deprecated-functions=off webtorrent=on"
          python3 setup.py install --user --prefix=

      - name: Build Python bindings (macOS)
        if: runner.os == 'macOS'
        run: |
          cd libtorrent/bindings/python
          python3.13 setup.py build_ext --b2-args "webtorrent=on"
          python3.13 setup.py install --install-lib $(brew --prefix)/lib/python3.13/site-packages

      - name: Build Python bindings (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          $env:BOOST_ROOT = "$pwd\boost"
          $env:BOOST_BUILD_PATH = "$env:BOOST_ROOT\tools\build"
          $env:PATH = "$env:BOOST_ROOT;$env:PATH"

          $libdata = "$pwd\libtorrent\deps\libdatachannel\install"
          $libPath = "$libdata\lib"
          $includePath = "$libdata\include"

          cd libtorrent/bindings/python
          python setup.py build_ext --b2-args `
            "msvc-version-macro=on" `
            "address-model=64" `
            "asserts=on" `
            "invariant-checks=full" `
            "webtorrent=on" `
            "library-path=\"$libPath\"" `
            "include-path=\"$includePath\"" `
            install --user --prefix=
