name: Windows Libtorrent Build

on:
  push:
  pull_request:

jobs:
  windows-build:
    runs-on: windows-2022
    name: Build Libtorrent Python (Windows)

    env:
      BOOST_VERSION: 1_83_0
      BOOST_DIR: C:\Libraries\boost_1_83_0
      OPENSSL_ROOT: C:\OpenSSL
      OPENSSL_VERSION: OpenSSL_1_1_1w
      PYTHON_DIR: C:\hostedtoolcache\windows\Python\3.13.5\x64

    steps:
      - name: Download source
        run: |
          git clone https://github.com/arvidn/libtorrent.git --depth=1 --recurse-submodules --branch master

      - name: Install dependencies
        run: |
          choco install strawberryperl ninja nasm -y
          python -m pip install --upgrade pip setuptools wheel

      - name: Build OpenSSL from source
        shell: cmd
        env:
          OPENSSL_ROOT: C:\OpenSSL
          OPENSSL_VERSION: OpenSSL_1_1_1w
        run: |
          set PATH=%PATH%;"C:\Program Files\NASM"
          git clone --branch %OPENSSL_VERSION% https://github.com/openssl/openssl.git
          cd openssl
          "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && ^
          perl Configure VC-WIN64A no-shared no-tests --prefix=%OPENSSL_ROOT% && ^
          nmake && ^
          nmake install_sw


      - name: install boost (windows)
        shell: cmd
        run: |
            cd libtorrent
            git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
            cd boost
            bootstrap.bat

      - name: boost headers (windows)
        shell: cmd
        run: |
            cd libtorrent\boost
            .\b2 headers

      - name: Set up Boost Python config
        run: |
          $py = "$env:PYTHON_DIR\python.exe"
          $version = & $py -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')"
          $include = "$env:PYTHON_DIR\include"
          $libs = "$env:PYTHON_DIR\libs"
          "using msvc ;`using python : $version : $py : $include : $libs ;" | Set-Content "$env:HOMEDRIVE$env:HOMEPATH\user-config.jam"
        shell: pwsh

      - name: Build libtorrent (b2)
        run: |
          b2 -j2 --hash ^
            openssl-lib=$env:OPENSSL_ROOT\lib ^
            openssl-include=$env:OPENSSL_ROOT\include ^
            warnings=all ^
            msvc address-model=64 ^
            picker-debugging=on invariant-checks=full ^
            variant=release link=static ^
            crypto=openssl webtorrent=on asserts=on export-extra=on ^
            windows-api=desktop windows-version=win10 cxxstd=17
        shell: cmd

      - name: Build Python bindings (stage)
        run: |
          cd bindings\python
          b2 -j2 --hash ^
            openssl-lib=$env:OPENSSL_ROOT\lib ^
            openssl-include=$env:OPENSSL_ROOT\include ^
            warnings=all ^
            msvc address-model=64 ^
            picker-debugging=on invariant-checks=full ^
            variant=release link=static ^
            crypto=openssl webtorrent=on asserts=on export-extra=on ^
            libtorrent-link=static stage_module stage_dependencies
        shell: cmd

      - name: Build Python wheel
        run: |
          cd bindings\python
          python setup.py bdist_wheel
        shell: cmd

      - name: Upload Python wheel
        uses: actions/upload-artifact@v4
        with:
          name: libtorrent-python-wheel
          path: bindings/python/dist/*.whl