name: Build libtorrent with Python bindings and WebTorrent support

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            - name: Install dependencies (Linux)
              if: runner.os == 'Linux'
              run: |
                  sudo apt update
                  sudo apt install -y \
                    build-essential cmake git \
                    libboost-all-dev libboost-python-dev \
                    libssl-dev libtool pkg-config \
                    python3-dev python3-pip \
                    python3-setuptools python3-wheel
                  python3 -m pip install wheel setuptools

            - name: Install dependencies (macOS)
              if: runner.os == 'macOS'
              run: |
                  brew install boost openssl cmake git websocketpp python@3.11
                  python3 -m pip install wheel setuptools

            - name: Install dependencies (Windows)
              if: runner.os == 'Windows'
              run: |
                  choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
                  choco install boost-msvc-14.3 python --version=3.11.4 -y
                  python -m pip install wheel setuptools

            - name: Install WebSocket++ (Linux/macOS only)
              if: runner.os != 'Windows'
              run: |
                  git clone https://github.com/zaphoyd/websocketpp.git
                  cd websocketpp
                  mkdir build && cd build
                  cmake ..
                  sudo make install

            - name: Clone libtorrent
              run: |
                  git clone --recurse-submodules https://github.com/arvidn/libtorrent.git
                  cd libtorrent
                  git checkout RC_2_0

            - name: Build libtorrent
              run: |
                  cd libtorrent
                  mkdir build && cd build
                  cmake .. `
                    -DCMAKE_BUILD_TYPE=Release `
                    -DBUILD_TESTING=OFF `
                    -DBUILD_EXAMPLES=OFF `
                    -DBUILD_TOOLS=OFF `
                    -DBUILD_PYTHON_BINDINGS=ON `
                    -DBUILD_WEBTORRENT=ON
                  cmake --build . --parallel

              shell: bash

            - name: Build Python bindings
              run: |
                  cd libtorrent/bindings/python
                  python setup.py bdist_wheel

              shell: bash

            - name: Upload Python wheel
              uses: actions/upload-artifact@v3
              with:
                  name: libtorrent-wheel-${{ runner.os }}
                  path: libtorrent/bindings/python/dist/*.whl
