name: Python bindings

on:
    push:
    pull_request:

env:
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
    test:
        name: build
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-24.04, macos-latest, windows-latest]

        steps:
            - name: Download source
              run: |
                  git clone https://github.com/arvidn/libtorrent.git --depth=1 --recurse-submodules --branch RC_2_0

            - name: dependencies (MacOS)
              if: runner.os == 'macOS'
              run: |
                  cd libtorrent
                  brew install boost-build boost boost-python3 python@3.13 openssl@3 python-setuptools
                  export PATH=$(brew --prefix)/opt/python@3.13/bin:$PATH

            - name: update package lists (linux)
              if: runner.os == 'Linux'
              continue-on-error: true
              run: |
                  cd libtorrent
                  sudo apt update

            - name: Setup ccache
              if: runner.os != 'Windows'
              uses: Chocobo1/setup-ccache-action@v1
              with:
                  update_packager_index: false
                  override_cache_key: ccache-python-${{ matrix.os }}-${{ github.base_ref }}
                  ccache_options: |
                      max_size=500M

            - name: dependencies (linux)
              if: runner.os == 'Linux'
              run: |
                  cd libtorrent
                  sudo apt install libboost-tools-dev libboost-python-dev libboost-dev libboost-system-dev python3 python3-setuptools libssl-dev nasm

            - name: Install Windows build tools
              if: runner.os == 'Windows'
              shell: powershell
              run: |
                  # Install Visual Studio Build Tools
                  choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"
                  choco install visualstudio2022-workload-nativedesktop -y
                  # Install OpenSSL
                  choco install openssl

            - name: Setup MSVC environment
              if: runner.os == 'Windows'
              uses: ilammy/msvc-dev-cmd@v1

            - name: install boost (windows)
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                  cd libtorrent
                  git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
                  cd boost
                  bootstrap.bat

            - name: boost headers (windows)
              if: runner.os == 'Windows'
              shell: cmd
              run: |
                  cd libtorrent\boost
                  .\b2 headers

            - name: build/install (Windows)
              if: runner.os == 'Windows'
              shell: pwsh
              run: |
                  cd libtorrent
                  cmake -B build -S . `
                    -DCMAKE_BUILD_TYPE=Release `
                    -Dpython-bindings=ON `
                    -Dwebtorrent=ON `
                    -Dbuild_tools=OFF `
                    -Dbuild_tests=OFF
                  cmake --build build --config Release
                  cd bindings/python
                  python -m pip install .

            - name: build no-deprecated (Linux)
              if: runner.os == 'Linux'
              run: |
                  cd libtorrent/bindings/python
                  python3 setup.py build_ext --b2-args "deprecated-functions=off link=static webtorrent=on"

            - name: build/install (Linux)
              if: runner.os == 'Linux'
              run: |
                  cd libtorrent
                  cmake -B build -S . \
                    -DCMAKE_BUILD_TYPE=Release \
                    -Dpython-bindings=ON \
                    -Dwebtorrent=ON \
                    -Dbuild_tools=OFF \
                    -Dbuild_tests=OFF
                  cmake --build build --config Release
                  cd bindings/python
                  python3 -m pip install .

            - name: build/install (MacOS)
              if: runner.os == 'macOS'
              run: |
                  cd libtorrent
                  export PATH=$(brew --prefix)/opt/python@3.13/bin:$PATH
                  cmake -B build -S . \
                    -DCMAKE_BUILD_TYPE=Release \
                    -Dpython-bindings=ON \
                    -Dwebtorrent=ON \
                    -Dbuild_tools=OFF \
                    -Dbuild_tests=OFF \
                    -DOPENSSL_ROOT_DIR=$(brew --prefix openssl)
                  cmake --build build --config Release
                  cd bindings/python
                  python3.13 -m pip install .
