# .github/workflows/build-libtorrent.yml
name: Build libtorrent (WebTorrent + Python) on Windows/Linux/macOS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: ${{ matrix.os }} build
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: '3.11'

            # ───── Dependencies ─────────────────────────────────────────────────────────
            - name: Install deps on Linux
              if: runner.os == 'Linux'
              run: |
                  sudo apt update
                  sudo apt install -y \
                    build-essential cmake git ninja-build \
                    libboost-all-dev libboost-python-dev \
                    libssl-dev python3-dev python3-pip
                  python3 -m pip install --upgrade wheel setuptools

            - name: Add swap on Linux (4 GB)
              if: runner.os == 'Linux'
              run: |
                  sudo fallocate -l 4G /swapfile
                  sudo chmod 600 /swapfile
                  sudo mkswap /swapfile
                  sudo swapon /swapfile

            - name: Install deps on macOS
              if: runner.os == 'macOS'
              run: |
                  brew update
                  brew install boost openssl cmake git ninja python@3.11
                  python3 -m pip install --upgrade wheel setuptools

            - name: Install deps on Windows
              if: runner.os == 'Windows'
              shell: pwsh
              run: |
                  choco install -y cmake --installargs '"ADD_CMAKE_TO_PATH=System"'
                  choco install -y boost-msvc-14.3 ninja
                  python -m pip install --upgrade wheel setuptools

            # ───── WebSocket++ ─────────────────────────────────────────────────────────
            - name: Install WebSocket++ (All Platforms)
              shell: bash
              run: |
                  git clone https://github.com/zaphoyd/websocketpp.git
                  cd websocketpp
                  mkdir build && cd build
                  cmake -G Ninja .. -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/websocketpp-install
                  ninja
                  ninja install

            # ───── libtorrent Checkout ──────────────────────────────────────────────────
            - name: Clone libtorrent
              run: |
                  git clone --recurse-submodules https://github.com/arvidn/libtorrent.git
                  cd libtorrent
                  git checkout RC_2_0

            # ───── Build core with Ninja ────────────────────────────────────────────────
            - name: Build libtorrent core
              shell: bash
              run: |
                  cd libtorrent
                  mkdir build && cd build
                  cmake -G Ninja .. \
                    -DCMAKE_BUILD_TYPE=Release \
                    -DBUILD_TESTING=OFF \
                    -DBUILD_EXAMPLES=ON \
                    -DBUILD_TOOLS=OFF \
                    -DBUILD_PYTHON_BINDINGS=ON \
                    -DBUILD_WEBTORRENT=ON \
                    -DWEBSOCKETPP_ROOT=$GITHUB_WORKSPACE/websocketpp-install
                  ninja

            # ───── Build Python wheel ───────────────────────────────────────────────────
            - name: Build Python bindings
              shell: bash
              run: |
                  cd libtorrent/bindings/python
                  python -m pip install --upgrade wheel setuptools
                  python setup.py bdist_wheel

            # ───── Upload artifact ─────────────────────────────────────────────────────
            - name: Upload wheel artifact
              uses: actions/upload-artifact@v4
              with:
                  name: libtorrent-wheel-${{ matrix.os }}
                  path: libtorrent/bindings/python/dist/*.whl
